sudo: true
dist: trusty

language: python

env:
  - KERAS_BACKEND=tensorflow
  - KERAS_BACKEND=theano
python:
  - 2.7
  - 3.6
services:
  - docker

before_install: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install: docker build --build-arg python_version=$TRAVIS_PYTHON_VERSION -t geo-docker -f Dockerfile .

script:  docker run --env KERAS_BACKEND=$KERAS_BACKEND --rm softwareunderground/geo-docker ipython;quit()

after_success:
  - docker images
  - docker tag geo-docker softwareunderground/geo-docker
  - docker push softwareunderground/geo-docker